name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -P $DOCKER_PASSWORD


    - name: Build the Docker image
      run: docker build -t cicd-pipeline .

    - name: Push your Docker Image
      run: docker push kene38/cicd-pipeline1:latest 
