name: Docker Image CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}


    - name: Build the Docker image
      run: docker build -t cicd-pipeline .

    - name: Push your Docker Image
      # run: docker push kene38/cicd-pipeline1
      run: docker push kene38/cicd-pipeline1:tagname
