name: Docker Image CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}


    - name: Build the Docker image
      run: docker build -t kene38/cicd-pipeline1 .

    - name: Push your Docker Image
      run: docker push kene38/cicd-pipeline1


  deploy:
    needs: build
    runs-on: aws-ec2

    steps:
      - name: Pull Docker Image
        run: sudo docker pull kene38/cicd-pipeline1:latest

      - name: Delete Old Container
        run: sudo rm -f Docker-Image-container 

      - name: Run Docker Image
        run: sudo docker run -d -p 8000:8000 --name Docker-Image-container kene38/cicd-pipeline1


