name: Docker Image CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Debug Secrets
      run: |
          echo "DOCKER_USERNAME: $DOCKER_USERNAME"
          echo "DOCKER_PASSWORD: $DOCKER_PASSWORD"

    - name: Login to Docker
      env:
            DOCKER_USERNAME: Kene38
            DOCKER_PASSWORD: Ihifix@Docker281
      run: |
            echo "DOCKER_USERNAME is set"
            docker login -u Kene38 -p Ihifix@Docker281


    - name: Build the Docker image
      run: docker build -t cicd-pipeline .

    - name: Push your Docker Image
      run: docker push kene38/cicd-pipeline1:latest 
